// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF52Ah0ERtBRalBWwAOgEMPUhjKrlpVvo',
    appId: '1:173382559812:web:3ea4ee55be2700c48d3411',
    messagingSenderId: '173382559812',
    projectId: 'brandsinfo-1ddff',
    authDomain: 'brandsinfo-1ddff.firebaseapp.com',
    storageBucket: 'brandsinfo-1ddff.firebasestorage.app',
    measurementId: 'G-JX8KS3LYPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBABeVo5KQuczrNhK7xhksVmoyBbiDyfoY',
    appId: '1:173382559812:android:8cca478f572683ca8d3411',
    messagingSenderId: '173382559812',
    projectId: 'brandsinfo-1ddff',
    storageBucket: 'brandsinfo-1ddff.firebasestorage.app',
  );
}
